CREATE TABLE IF NOT EXISTS User (
    id BIGINT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
);

CREATE TABLE IF NOT EXISTS Bot (
    id BIGINT NOT NULL PRIMARY KEY,
    botName TEXT NOT NULL,
    ownerId BIGINT NOT NULL,
    token TEXT NOT NULL,
    FOREIGN KEY (ownerId) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Heartbeat (
    botId BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    FOREIGN KEY (botId) REFERENCES Bot(id)
);