CREATE TABLE IF NOT EXISTS User (
    id BIGINT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Bot (
    id BIGINT NOT NULL PRIMARY KEY,
    ownerId BIGINT,
    token TEXT,
    FOREIGN KEY (ownerId) REFERENCES User(id)
);

CREATE TABLE IF NOT EXISTS Heartbeat (
    botId BIGINT NOT NULL,
    timestamp BIGINT NOT NULL,
    FOREIGN KEY (botId) REFERENCES Bot(id)
);